### ISSUE TITLE
Cannot read TOC after rendering with contrib.toc_renderer

### ISSUE THREAD

**Issue by andy0130tw** [miyuchina/mistletoe#88]
I just came across for surveying some CommonMark implementations in Python and noticed the TOC feature. It seems nice, but unfortunately I couldn't get it to work. Here is the minimal reproduction of this bug:

Setup:

```bash
git clone https://github.com/miyuchina/mistletoe
cd mistletoe
pip install -e
```

In this directory, run the following code:

```python
from contrib.toc_renderer import TOCRenderer
from mistletoe import Document
with TOCRenderer() as r:
    r.render(Document('# aaa\n## bbb'))
print(r.toc)
```

The last line try to access the TOC tokens, raising an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/mistletoe/contrib/toc_renderer.py", line 45, in toc
    return List([build_list_item(heading) for heading in self._headings])
  File "/tmp/mistletoe/mistletoe/block_token.py", line 453, in __init__
    self.children = [ListItem(*match) for match in matches]
  File "/tmp/mistletoe/mistletoe/block_token.py", line 453, in <listcomp>
    self.children = [ListItem(*match) for match in matches]
TypeError: __init__() takes 4 positional arguments but 7 were given
```

7 is because `# aaa` is transformed to (2 spaces + `- aaa`), which has a length of 7.

Maybe the implementation changes so that `block_token.ListItem` now receives fixed number of arguments instead of plain `str`? Also note that the corresponding test:

https://github.com/miyuchina/mistletoe/blob/master/test/test_contrib/test_toc_renderer.py#L43-L59

Does not test this feature thoroughly. It uses a mocked object and will succeed anyways.

**Comment by andy0130tw** [comment]
Here is an ad-hoc patch to `contrib.TOCRenderer`:

```diff
      @property
      def toc(self):
#         (omitted)

-         return List([build_list_item(heading) for heading in self._headings])
+         lines = [build_list_item(heading) for heading in self._headings]
+         items = block_token.tokenize(lines)
+         return items[0]
```

**Comment by pbodnar** [comment]
Thanks for the report and the proposed fix.

I can confirm that surprisingly the unit tests really do not test the whole scenario. That's why they didn't reveal the error of passing quite different arguments into the `List` constructor than actually expected (list of strings vs. list of tuples).
